services:
  stub:
    image: nexus.cainc.com:5000/cainc/yriahi/swiss-army-image:latest
    ports:
      - "80:80"
      - "8080:8080"
      - "8181:8181"
      - "8081:8081"
      - "3000:3000"
      - "5000:5000"
